using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MojProjekt.Application.Search;

namespace MojProjekt.Infrastructure.Ai.Anthropic;

/// <summary>
/// Turns a natural-language query into structured SearchCriteria using Claude's tool-use (forced
/// function calling) rather than asking for free-form JSON in the prompt — this is the guardrail
/// that keeps the AI's output structurally reliable. Falls back to NaiveCriteriaExtractor whenever
/// no API key is configured, the call fails/times out, or the model doesn't invoke the tool, so
/// search always stays usable even without AI. Match reasons are never generated by this class —
/// only structured criteria — so "why this matched" stays traceable to deterministic ranking code
/// (see ListingRankingService), never hallucinated by the model.
/// </summary>
public class AnthropicQueryInterpreter(
    HttpClient httpClient, IOptions<AnthropicOptions> options, ILogger<AnthropicQueryInterpreter> logger)
    : INaturalLanguageQueryInterpreter
{
    private const string ToolName = "extract_search_criteria";

    private const string SystemPrompt =
        "You translate a car buyer's natural-language search into structured criteria for filtering a " +
        "local database of car listings. Only extract what the user actually stated or clearly implied; " +
        "leave a field unset if it isn't mentioned. Mark a preference as required=true only when the user " +
        "used language like 'must', 'has to be', 'only'; use required=false for soft preferences like " +
        "'preferably', 'ideally', 'would like'. Always include a one-sentence intentSummary restating " +
        "what you understood the user is looking for, in plain English.";

    public async Task<QueryInterpretationResult> InterpretAsync(string query, CancellationToken cancellationToken)
    {
        if (!options.Value.IsConfigured)
        {
            return FallbackResult(query, "No Anthropic API key configured.");
        }

        for (var attempt = 1; attempt <= 2; attempt++)
        {
            try
            {
                var payload = await CallAnthropicAsync(query, attempt, cancellationToken);
                if (payload is null)
                {
                    continue; // Tool wasn't invoked or response was malformed; retry once with a stricter nudge.
                }

                var (criteria, validationWarnings) = CriteriaValidator.Validate(payload);
                return new QueryInterpretationResult(
                    criteria,
                    string.IsNullOrWhiteSpace(payload.IntentSummary) ? "Interpreted your search criteria." : payload.IntentSummary,
                    validationWarnings,
                    UsedFallbackExtraction: false);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                logger.LogWarning(ex, "Anthropic query interpretation attempt {Attempt} failed.", attempt);
            }
        }

        return FallbackResult(query, "AI query interpretation failed after retrying.");
    }

    private async Task<ExtractedCriteriaPayload?> CallAnthropicAsync(string query, int attempt, CancellationToken cancellationToken)
    {
        var request = new AnthropicRequest
        {
            Model = options.Value.Model,
            MaxTokens = 1024,
            System = attempt == 1 ? SystemPrompt : SystemPrompt + " You MUST call the extract_search_criteria tool with your answer.",
            Messages = [new AnthropicMessage { Role = "user", Content = query }],
            Tools = [BuildToolDefinition()],
            ToolChoice = new JsonObject { ["type"] = "tool", ["name"] = ToolName }
        };

        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, "/v1/messages")
        {
            Content = JsonContent.Create(request)
        };
        httpRequest.Headers.Add("x-api-key", options.Value.ApiKey);
        httpRequest.Headers.Add("anthropic-version", "2023-06-01");
        httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        using var httpResponse = await httpClient.SendAsync(httpRequest, cancellationToken);
        httpResponse.EnsureSuccessStatusCode();

        var response = await httpResponse.Content.ReadFromJsonAsync<AnthropicResponse>(cancellationToken: cancellationToken);
        var toolUseBlock = response?.Content.FirstOrDefault(b => b.Type == "tool_use" && b.Name == ToolName);

        return toolUseBlock?.Input?.Deserialize<ExtractedCriteriaPayload>(
            new JsonSerializerOptions(JsonSerializerDefaults.Web));
    }

    private static QueryInterpretationResult FallbackResult(string query, string reason)
    {
        var criteria = NaiveCriteriaExtractor.Extract(query);
        return new QueryInterpretationResult(
            criteria,
            "Interpreted using simplified keyword matching (AI interpretation unavailable).",
            [reason],
            UsedFallbackExtraction: true);
    }

    private static AnthropicTool BuildToolDefinition() => new()
    {
        Name = ToolName,
        Description = "Extract structured car search criteria from a natural-language query.",
        InputSchema = JsonNode.Parse("""
        {
          "type": "object",
          "properties": {
            "intentSummary": { "type": "string", "description": "One-sentence plain-English restatement of what the user is looking for." },
            "priceMin": { "type": "number", "description": "Minimum price in PLN, if the user gave one." },
            "priceMax": { "type": "number", "description": "Maximum price / budget in PLN, if the user gave one." },
            "yearMin": { "type": "integer", "description": "Earliest acceptable model year, e.g. from 'no older than 2019'." },
            "yearMax": { "type": "integer", "description": "Latest acceptable model year, if stated." },
            "mileageMax": { "type": "integer", "description": "Maximum mileage in kilometers, if stated." },
            "transmission": { "type": "string", "enum": ["Manual", "Automatic"] },
            "transmissionRequired": { "type": "boolean", "description": "True only if the user said transmission must/has to match; false for soft preferences like 'preferably'." },
            "fuelType": { "type": "string", "enum": ["Petrol", "Diesel", "Electric", "Hybrid", "Lpg"] },
            "fuelTypeRequired": { "type": "boolean" },
            "bodyType": { "type": "string", "enum": ["Sedan", "Estate", "Hatchback", "Suv", "Coupe", "Van", "Pickup", "Convertible"] },
            "bodyTypeRequired": { "type": "boolean" },
            "brand": { "type": "string", "description": "Car brand/make, if mentioned." },
            "model": { "type": "string", "description": "Car model, if mentioned." },
            "keywords": {
              "type": "array",
              "items": { "type": "string" },
              "description": "Other descriptive words from the query worth matching against listing text, e.g. 'reliable', 'family'."
            }
          },
          "required": ["intentSummary"]
        }
        """)!.AsObject()
    };
}
